/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallRoom {
  'participants' : Array<UserId>,
  'roomUrl' : string,
  'createdAt' : Timestamp,
  'callType' : CallType,
  'roomId' : string,
}
export type CallType = { 'video' : null } |
  { 'voice' : null };
export interface Channel {
  'id' : ChannelId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export type ChannelId = bigint;
export interface ChannelPost {
  'id' : bigint,
  'postedAt' : Timestamp,
  'content' : string,
  'channelId' : ChannelId,
  'authorId' : UserId,
}
export interface Group {
  'id' : GroupId,
  'members' : Array<GroupMember>,
  'name' : string,
  'createdAt' : Timestamp,
  'creatorId' : UserId,
}
export type GroupId = bigint;
export interface GroupMember {
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'isAdmin' : boolean,
}
export type MediaType = { 'audio' : null } |
  { 'video' : null } |
  { 'none' : null } |
  { 'image' : null };
export interface MediaUploadCertificate {
  'method' : string,
  'blobHash' : string,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'mediaUrl' : [] | [string],
  'timestamp' : Timestamp,
  'mediaType' : MediaType,
  'senderId' : UserId,
}
export type MessageId = bigint;
export type PaymentId = bigint;
export interface PayoutRequest {
  'id' : PaymentId,
  'status' : PayoutStatus,
  'totalAmount' : bigint,
  'requestedAt' : Timestamp,
}
export type PayoutStatus = { 'pending' : null } |
  { 'processed' : null };
export type StatusId = bigint;
export interface StatusPost {
  'id' : StatusId,
  'content' : string,
  'expiresAt' : Timestamp,
  'authorId' : UserId,
  'createdAt' : Timestamp,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'realName' : string,
  'createdAt' : Timestamp,
  'isVerified' : boolean,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationRequest {
  'status' : VerificationStatus,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'receiptStorageKey' : string,
  'verifiedAt' : [] | [Timestamp],
}
export type VerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addGroupMember' : ActorMethod<[GroupId, UserId], undefined>,
  'adminApproveVerification' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetTotalRevenue' : ActorMethod<[], bigint>,
  'adminListPayoutRequests' : ActorMethod<[], Array<PayoutRequest>>,
  'adminListUsers' : ActorMethod<[], Array<UserProfile>>,
  'adminListVerificationRequests' : ActorMethod<[], Array<VerificationRequest>>,
  'adminRejectVerification' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRequestPayout' : ActorMethod<[], PayoutRequest>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCallRoom' : ActorMethod<
    [UserId, CallType],
    { 'ok' : CallRoom } |
      { 'err' : string }
  >,
  'createChannel' : ActorMethod<[string, string], Channel>,
  'createCheckoutSession' : ActorMethod<
    [
      Array<
        {
          'productName' : string,
          'currency' : string,
          'quantity' : bigint,
          'priceInCents' : bigint,
          'productDescription' : string,
        }
      >,
      string,
      string,
    ],
    string
  >,
  'createGroup' : ActorMethod<[string], Group>,
  'createStatusPost' : ActorMethod<[string], StatusPost>,
  'deleteStatusPost' : ActorMethod<[StatusId], undefined>,
  'getActiveStatusPosts' : ActorMethod<[], Array<StatusPost>>,
  'getCallRoom' : ActorMethod<[string], [] | [CallRoom]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelPosts' : ActorMethod<[ChannelId], Array<ChannelPost>>,
  'getDirectMessages' : ActorMethod<[UserId], Array<Message>>,
  'getGroup' : ActorMethod<[GroupId], [] | [Group]>,
  'getGroupMessages' : ActorMethod<[GroupId], Array<Message>>,
  'getMediaDownloadUrl' : ActorMethod<[string], string>,
  'getMyVerificationRequest' : ActorMethod<[], [] | [VerificationRequest]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserByPhone' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'leaveGroup' : ActorMethod<[GroupId], undefined>,
  'listChannels' : ActorMethod<[], Array<Channel>>,
  'listMyGroups' : ActorMethod<[], Array<Group>>,
  'postToChannel' : ActorMethod<[ChannelId, string], ChannelPost>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'requestMediaUploadUrl' : ActorMethod<[string], MediaUploadCertificate>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDirectMessage' : ActorMethod<
    [UserId, string, [] | [string], MediaType],
    Message
  >,
  'sendGroupMessage' : ActorMethod<
    [GroupId, string, [] | [string], MediaType],
    Message
  >,
  'setDailyApiKey' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitVerificationRequest' : ActorMethod<
    [string],
    { 'ok' : VerificationRequest } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];