/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GroupId = IDL.Nat;
export const UserId = IDL.Principal;
export const PaymentId = IDL.Nat;
export const PayoutStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const PayoutRequest = IDL.Record({
  'id' : PaymentId,
  'status' : PayoutStatus,
  'totalAmount' : IDL.Nat,
  'requestedAt' : Timestamp,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'realName' : IDL.Text,
  'createdAt' : Timestamp,
  'isVerified' : IDL.Bool,
  'phone' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VerificationRequest = IDL.Record({
  'status' : VerificationStatus,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'receiptStorageKey' : IDL.Text,
  'verifiedAt' : IDL.Opt(Timestamp),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
export const CallRoom = IDL.Record({
  'participants' : IDL.Vec(UserId),
  'roomUrl' : IDL.Text,
  'createdAt' : Timestamp,
  'callType' : CallType,
  'roomId' : IDL.Text,
});
export const ChannelId = IDL.Nat;
export const Channel = IDL.Record({
  'id' : ChannelId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const GroupMember = IDL.Record({
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'isAdmin' : IDL.Bool,
});
export const Group = IDL.Record({
  'id' : GroupId,
  'members' : IDL.Vec(GroupMember),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'creatorId' : UserId,
});
export const StatusId = IDL.Nat;
export const StatusPost = IDL.Record({
  'id' : StatusId,
  'content' : IDL.Text,
  'expiresAt' : Timestamp,
  'authorId' : UserId,
  'createdAt' : Timestamp,
});
export const ChannelPost = IDL.Record({
  'id' : IDL.Nat,
  'postedAt' : Timestamp,
  'content' : IDL.Text,
  'channelId' : ChannelId,
  'authorId' : UserId,
});
export const MessageId = IDL.Nat;
export const MediaType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'none' : IDL.Null,
  'image' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'mediaType' : MediaType,
  'senderId' : UserId,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const MediaUploadCertificate = IDL.Record({
  'method' : IDL.Text,
  'blobHash' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
  'adminApproveVerification' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'adminListPayoutRequests' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'adminListVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'adminRejectVerification' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRequestPayout' : IDL.Func([], [PayoutRequest], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCallRoom' : IDL.Func(
      [UserId, CallType],
      [IDL.Variant({ 'ok' : CallRoom, 'err' : IDL.Text })],
      [],
    ),
  'createChannel' : IDL.Func([IDL.Text, IDL.Text], [Channel], []),
  'createCheckoutSession' : IDL.Func(
      [
        IDL.Vec(
          IDL.Record({
            'productName' : IDL.Text,
            'currency' : IDL.Text,
            'quantity' : IDL.Nat,
            'priceInCents' : IDL.Nat,
            'productDescription' : IDL.Text,
          })
        ),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createGroup' : IDL.Func([IDL.Text], [Group], []),
  'createStatusPost' : IDL.Func([IDL.Text], [StatusPost], []),
  'deleteStatusPost' : IDL.Func([StatusId], [], []),
  'getActiveStatusPosts' : IDL.Func([], [IDL.Vec(StatusPost)], ['query']),
  'getCallRoom' : IDL.Func([IDL.Text], [IDL.Opt(CallRoom)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelPosts' : IDL.Func([ChannelId], [IDL.Vec(ChannelPost)], ['query']),
  'getDirectMessages' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
  'getGroupMessages' : IDL.Func([GroupId], [IDL.Vec(Message)], ['query']),
  'getMediaDownloadUrl' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getMyVerificationRequest' : IDL.Func(
      [],
      [IDL.Opt(VerificationRequest)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveGroup' : IDL.Func([GroupId], [], []),
  'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'listMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'postToChannel' : IDL.Func([ChannelId, IDL.Text], [ChannelPost], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestMediaUploadUrl' : IDL.Func([IDL.Text], [MediaUploadCertificate], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendDirectMessage' : IDL.Func(
      [UserId, IDL.Text, IDL.Opt(IDL.Text), MediaType],
      [Message],
      [],
    ),
  'sendGroupMessage' : IDL.Func(
      [GroupId, IDL.Text, IDL.Opt(IDL.Text), MediaType],
      [Message],
      [],
    ),
  'setDailyApiKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitVerificationRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : VerificationRequest, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GroupId = IDL.Nat;
  const UserId = IDL.Principal;
  const PaymentId = IDL.Nat;
  const PayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const PayoutRequest = IDL.Record({
    'id' : PaymentId,
    'status' : PayoutStatus,
    'totalAmount' : IDL.Nat,
    'requestedAt' : Timestamp,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'realName' : IDL.Text,
    'createdAt' : Timestamp,
    'isVerified' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VerificationRequest = IDL.Record({
    'status' : VerificationStatus,
    'userId' : UserId,
    'submittedAt' : Timestamp,
    'receiptStorageKey' : IDL.Text,
    'verifiedAt' : IDL.Opt(Timestamp),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
  const CallRoom = IDL.Record({
    'participants' : IDL.Vec(UserId),
    'roomUrl' : IDL.Text,
    'createdAt' : Timestamp,
    'callType' : CallType,
    'roomId' : IDL.Text,
  });
  const ChannelId = IDL.Nat;
  const Channel = IDL.Record({
    'id' : ChannelId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const GroupMember = IDL.Record({
    'userId' : UserId,
    'joinedAt' : Timestamp,
    'isAdmin' : IDL.Bool,
  });
  const Group = IDL.Record({
    'id' : GroupId,
    'members' : IDL.Vec(GroupMember),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'creatorId' : UserId,
  });
  const StatusId = IDL.Nat;
  const StatusPost = IDL.Record({
    'id' : StatusId,
    'content' : IDL.Text,
    'expiresAt' : Timestamp,
    'authorId' : UserId,
    'createdAt' : Timestamp,
  });
  const ChannelPost = IDL.Record({
    'id' : IDL.Nat,
    'postedAt' : Timestamp,
    'content' : IDL.Text,
    'channelId' : ChannelId,
    'authorId' : UserId,
  });
  const MessageId = IDL.Nat;
  const MediaType = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'none' : IDL.Null,
    'image' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'mediaType' : MediaType,
    'senderId' : UserId,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const MediaUploadCertificate = IDL.Record({
    'method' : IDL.Text,
    'blobHash' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
    'adminApproveVerification' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'adminListPayoutRequests' : IDL.Func(
        [],
        [IDL.Vec(PayoutRequest)],
        ['query'],
      ),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'adminListVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'adminRejectVerification' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRequestPayout' : IDL.Func([], [PayoutRequest], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCallRoom' : IDL.Func(
        [UserId, CallType],
        [IDL.Variant({ 'ok' : CallRoom, 'err' : IDL.Text })],
        [],
      ),
    'createChannel' : IDL.Func([IDL.Text, IDL.Text], [Channel], []),
    'createCheckoutSession' : IDL.Func(
        [
          IDL.Vec(
            IDL.Record({
              'productName' : IDL.Text,
              'currency' : IDL.Text,
              'quantity' : IDL.Nat,
              'priceInCents' : IDL.Nat,
              'productDescription' : IDL.Text,
            })
          ),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createGroup' : IDL.Func([IDL.Text], [Group], []),
    'createStatusPost' : IDL.Func([IDL.Text], [StatusPost], []),
    'deleteStatusPost' : IDL.Func([StatusId], [], []),
    'getActiveStatusPosts' : IDL.Func([], [IDL.Vec(StatusPost)], ['query']),
    'getCallRoom' : IDL.Func([IDL.Text], [IDL.Opt(CallRoom)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelPosts' : IDL.Func(
        [ChannelId],
        [IDL.Vec(ChannelPost)],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
    'getGroupMessages' : IDL.Func([GroupId], [IDL.Vec(Message)], ['query']),
    'getMediaDownloadUrl' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getMyVerificationRequest' : IDL.Func(
        [],
        [IDL.Opt(VerificationRequest)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveGroup' : IDL.Func([GroupId], [], []),
    'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'listMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'postToChannel' : IDL.Func([ChannelId, IDL.Text], [ChannelPost], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestMediaUploadUrl' : IDL.Func(
        [IDL.Text],
        [MediaUploadCertificate],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendDirectMessage' : IDL.Func(
        [UserId, IDL.Text, IDL.Opt(IDL.Text), MediaType],
        [Message],
        [],
      ),
    'sendGroupMessage' : IDL.Func(
        [GroupId, IDL.Text, IDL.Opt(IDL.Text), MediaType],
        [Message],
        [],
      ),
    'setDailyApiKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitVerificationRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : VerificationRequest, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };